### ISSUE TITLE
An unreliable way of defining an infinite horde

### ISSUE THREAD

**Issue by BRU7U5** [TouchMe-Inc/l4d2_tank_infinity_horde_control#1]
https://github.com/TouchMe-Inc/l4d2_tank_infinity_horde_control/blob/eb67a35803cace3a64af090393422e18e82af87f/addons/scripting/tank_infinity_horde_control.sp#L205

Current method works well only on configs (versus gamemodes) where is random spawning hordes are disabled. Most of vanilla (T1) versus servers have no disabled random hordes. This thing will occur situations when after random spawned horde (by timer) or by mini-events (ex. c11m4 mini-van) this plugin will start counting that infinite mob are started and may block them if Tank will be alive.

**Comment by TouchMe-Inc** [comment]
There is no better method than this (provided I don't intercept vscript and func_button events or other triggers). 
This plugin is considered a reimagining of the original plugin and does not claim to be more.
Sorry
